/** Лимиты загрузки файлов заявления (синхронизировать с src/config/upload-limits.js) */
const MB = 1024 * 1024;

const MAX_APPLICATION_FILE_BYTES = 10 * MB;
const MAX_APPLICATION_SUBMIT_TOTAL_BYTES = 50 * MB;
const MAX_APPLICATION_SUBMIT_FILES = 5;
const RECOMMENDED_NGINX_BODY_BYTES = 60 * MB;

module.exports = {
  MB,
  MAX_APPLICATION_FILE_BYTES,
  MAX_APPLICATION_SUBMIT_TOTAL_BYTES,
  MAX_APPLICATION_SUBMIT_FILES,
  RECOMMENDED_NGINX_BODY_BYTES,
  MAX_APPLICATION_FILE_MB: 10,
  MAX_APPLICATION_SUBMIT_TOTAL_MB: 50,
};
